charts/controller/templates/_helpers.tmpl
As of kubernetes 1.8 RBAC is now stable and the endpoint has changed to rbac.authorization.k8s.io/v1 . I have kept compatibility for older k8s versions. 
This is my first PR, let me know if something is missing!
List of PRs related to this:
controller: teamhephy/controller#6
router: teamhephy/router#5
monitor: teamhephy/monitor#1
fluentd: teamhephy/fluentd#2
builder: teamhephy/builder#1
=> add support for rbac v1 API endpoint

charts/controller/templates/_helpers.tmpl
This fixes an issue with the latest Kube version 1.10 where "9" is greater than "10" because of string comparison rules
The RBAC roles were failing to be created because KubeMinor was not compared as integer.  There's also semverCompare that we could have used, but behavior of the GitVersion proved to be less repeatable across versions than the KubeMinor int.
(In particular the latest version of minikube seems to be confused about Capabilities.KubeVersion.GitVersion, I got "v1.9.0" on the latest minikube with K8S v1.10.0 deployed.)
=> fix(charts): int cast in version comparison

charts/controller/templates/_helpers.tmpl
This fixes what we experiencing on GKE testing today where kubeVersions can be 1.9+ and our helm int casting fails.
Thanks to prometheus-operator for the idea: coreos/prometheus-operator#1729
=> fix(charts): set rbac apiVersion without casting

rootfs/api/migrations/0028_config_termination_grace_period.py
Fixing the conflicting migrations without using django's `python3 manage.py makemigrations --merge` . Personal taste.
=> fix(api/migrations): fix migrations conflict without merge

rootfs/requirements.txt
Updating `Django` to newer version and `pyOpenSSL` in order to address security vulnerabilities. Also we need to address some code in order to upgrade `djangorestframework` package: https://github.com/teamhephy/controller/issues/80
=> chore(requirements): updating django version and dependencies

rootfs/requirements.txt
Updating requests package to 2.20.0 because of discovered vulnerability [CVE-2018-18074](https://nvd.nist.gov/vuln/detail/CVE-2018-18074)
=> chore(requirements): updating requests package for vulnerability

rootfs/requirements.txt, rootfs/scheduler/__init__.py, rootfs/scheduler/resources/deployment.py, rootfs/scheduler/tests/test_deployments.py, rootfs/scheduler/tests/test_horizontalpodautoscaler.py, rootfs/scheduler/tests/test_horizontalpodautoscaler_12_lower.py
closes https://github.com/teamhephy/workflow/issues/73
Requires manual edit on the deployment: 
```
kubectl edit deployment rocksolidapp-web -n rocksolidapp
```
Then edit the part:
```
...
spec:
(...skipping top parts...)
template:
metadata:
annotations:
iam.amazonaws.com/role: role-arn-pods
nginx.ingress.kubernetes.io/app-root: /rootfs
sidecar.istio.io/inject: "true"
creationTimestamp: null
labels:
app: rocksolidapp
heritage: deis
type: web
version: v39
name: rocksolidapp-web
namespace: rocksolidapp
```
and add the annotations on the `deployment['spec']['template']['metadata']['annotations']` and the controller preserves these annotations for all releases after that. :anchor: 
After a new release or scale event the Pods of an app will have this yaml:
```
apiVersion: v1
kind: Pod …
```
=> feat(deployment.py): add support fo annotations to deployments and carry forward

rootfs/api/models/app.py, rootfs/api/models/release.py, rootfs/api/tests/test_app.py, rootfs/api/tests/test_build.py, rootfs/api/tests/test_config.py, rootfs/api/tests/test_healthchecks.py, rootfs/api/tests/test_hooks.py, rootfs/api/tests/test_pods.py, rootfs/api/tests/test_registry.py, rootfs/api/tests/test_release.py, rootfs/registry/__init__.py, rootfs/registry/dockerclient.py
resolves https://github.com/teamhephy/workflow/issues/78
Essentially, this just attempts a `docker_client.inspect_image` (which downloads just the manifest, not the whole image) on `deis pull` and that raises an error if it's a private registry and the user didn't add the correct credentials to the app.
I think in the default hephy install, with the on-cluster `deis-registry`, you can still "steal" other users' source build images by doing `deis pull 127.0.0.1:5555/hephy/some-app:git-$githash`. But for that to work, you'd need to somehow guess the app name *and* the correct git hash - I don't think that's very likely. Plus, that stops working if you use a password-protected off-cluster registry for hephy.
=> check image access on `deis pull`

rootfs/scheduler/resources/deployment.py
This reverts commit a226971e4d7bb06850704b7c86ca463ff1b77fec.
Users on GKE experience an issue with this change, because the cluster Minor version is usually (9+) or (11+) not parseable in semver. #92 
Users on AKS experience an issue with this change that disables `deis ps:scale` #93 – the cause is unknown, since AKS version numbers are parseable; the error message in the linked issue seems to indicate that "Scale" has moved, so I'm not sure it's as easy as this PR makes it out to be.  In earlier versions, the Scale resource was under `extensions/v1beta2` with the Deployment resource.  In this version, it looks like it lives in the `autoscaling/v1` API group.
This is a problem because our code assumes that the Scale resource/kind lives in the same API group as the Deployment kind, now …
=> Revert "set deployment API to apps/v1 if k8s >= 1.9"

rootfs/scheduler/resources/pod.py
Ignore pod scheduling failures if the `DEIS_IGNORE_SCHEDULING_FAILURE` environment variable is set.
Pod scheduling errors during deployments, especially in autoscaled clusters, are often temporary. That's why we want to be able to ignore them.
Signed-off-by: Johann Fuechsl <johann@fuechsl.co>
=> Ignore pod scheduling errors during deployments

rootfs/scheduler/resources/deployment.py
`is not` is the way to compare objects but not numbers, now it works only because of this https://stackoverflow.com/questions/306313/is-operator-behaves-unexpectedly-with-integers. Once number of pods become more than 256 it stops working
=> Fix deployment status validation when number of pods more than 256

rootfs/requirements.txt
Bumps django from 1.11.23 to 1.11.27.
=> chore(deps): bump django from 1.11.23 to 1.11.27 in /rootfs

rootfs/Dockerfile
Ran into these errors during testing on controller startup:
```
ModuleNotFoundError: No module named 'distutils.util'
Django Version: 
Python 3.6.9
Django checks:
Traceback (most recent call last):
File "/app/manage.py", line 12, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 308, in execute
settings.INSTALLED_APPS
File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 56, in __getattr__
self._setup(name)
File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 41, in _setup …
```
=> fix(Dockerfile): fix django python3-distutils on bionic 18.04

rootfs/Dockerfile, rootfs/Dockerfile.test
Sync with the latest base image.
=> chore(rootfs): bump to hephy/base:v0.4.1 base image

rootfs/scheduler/resources/pod.py
Fix a crash during "deis run", when some pod events are missing a timestamp, see: https://github.com/kubernetes/kubernetes/issues/89689
Without this bugfix error like this can show up during deployments or deis run on Kubernetes 1.17.x:
Deployment:
> `Unknown Error (400): {"detail":"(app::deploy): unorderable types: str() < NoneType()"}`
Run:
> `Error: Unknown Error (503): {"detail":"my-app-run-x47pk (run): '<' not supported between instances of 'str' and 'NoneType'"}`
This bugfix has been verified to fix the "deis run" errors, but will likely fix the same error during deployment, since no other codepaths seem to sort event timestamps.
The deployment error doesn't happen every time, so some time is requried to see, if it is also fixed.
=> fix(scheduler): handle missing timestamps in pod events

rootfs/scheduler/resources/deployment.py
This PR adds retry logic in `_check_for_failed_events` in the case where a race-condition could cause a ReplicaSet that's being created to not be available yet.
=> fix(controller): Retry on potential ReplicaSet create race-condition.

rootfs/scheduler/resources/deployment.py, rootfs/scheduler/tests/test_deployments.py, rootfs/scheduler/tests/test_horizontalpodautoscaler.py, rootfs/scheduler/tests/test_horizontalpodautoscaler_12_lower.py
This PR sets the number of replicas to the current number of replicas when updating a deployment. This prevents disruptive scaling activities when auto-scaling is enabled.
=> fix(controller): Set replicas to the current value of the deployment.

README.md, charts/controller/Chart.yaml, charts/controller/templates/controller-deployment.yaml, rootfs/scheduler/mock.py, rootfs/scheduler/resources/deployment.py, rootfs/scheduler/resources/ingress.py, rootfs/scheduler/resources/replicaset.py, rootfs/scheduler/tests/test_deployments.py
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Per the above recent blog post we need to migrate some of our APIs to work with the deprecations in k8s 1.16 .
Would really appreciate if other people looked at these changes and try to fix the broken tests. For now overwriting some url generations in the mock.py should fix the tests. We still have broken tests with these changes.
Steps to get a working development Django/Python environment:
1. Install Postgresql local database and initialize with `postgres` user then edit `/var/lib/pgsql/data/pg_hba.conf` to allow local connections
2. Install local django and python dependencies in `/rootfs`
```bash # Updating the Django version:
$ pip3 install -r requirements.txt --user
```
3. Set these environment variables and make sure …
=> Feature/fix deprecated apis 1.16

README.md, charts/controller/Chart.yaml, charts/controller/templates/_helpers.tmpl, charts/controller/templates/controller-clusterrole.yaml, charts/controller/templates/controller-deployment.yaml, rootfs/scheduler/mock.py, rootfs/scheduler/resources/deployment.py, rootfs/scheduler/resources/ingress.py, rootfs/scheduler/resources/replicaset.py, rootfs/scheduler/tests/test_deployments.py
This is the last PR to submit in the series upgrading the charts for K8s 1.16 in Hephy Workflow v2.23, unless I missed one.
This probably should not be merged without validating the e2e suite, I think that does not need any upgrade though because it does not deploy, only creates a Pod which was already at v1 quite some time ago.
I believe that this will not work without further RBAC changes that must be made in a later commit. I have not done enough research to say what must change exactly. There are also further changes needed in router based on my testing, but again I can't say exactly what is needed just yet.
See teamhephy/monitor#14 for more details about the change, which is the first PR opened in the series.  The full list of associated PRs is as follows:
requires …
=> chore(controller): permit umbrella override api group

charts/controller/templates/controller-clusterrole.yaml, rootfs/scheduler/resources/scale.py
~Affects charts only~. Fixes this error:
```
User \"system:serviceaccount:deis:deis-controller\" cannot update resource \"deployments/scale\" in API group \"apps\"
```
Quite unhelpfully, the error messaging says "cannot update" here when it evidently means to warn you that it "cannot PATCH" in the HTTP verb parlance. I wonder if this "cannot update" language is our string, or if it came from upstream libraries?
=> fix(charts): controller needs the "patch" perm

rootfs/api/models/app.py
The old `extensions/v1beta1` string for Deployment API was hardcoded here. If you are using autoscale and haven't upgraded to a cluster version with apps/v1 yet, it's time. There is no permanent support for extensions/v1beta1 from here forward (and I believe this is actually the first patch that strictly breaks backwards compatibility.)
=> fix(controller): apps/v1 in App model for hpa

Makefile, rootfs/api/management/commands/healthchecks.py, rootfs/api/management/commands/load_db_state_to_k8s.py
resolves #135 
@dmcnaught @kingdonb 
Local unit test and local minikube testing passes for me. Had to modify the function.
There are multiple appsettings per app. We only care about the latest one. We use app.structure for the proc_types only if appsettings.autoscale is set. If autoscale is unset on deis, then the hpa should not be created and should return an error.
This is the intended behaviour as we assume deis/hephy controller is master of its own namespaces (apps).
=> feat(HPAs): resolves #135 recreate HPAs from db on load

charts/controller/templates/controller-deployment.yaml, charts/controller/values.yaml
permit setting GUNICORN_WORKERS
This is the chart-only change. #75 had another separate change for CONN_MAX_AGE, but I could not get controller to build tonight... this variable is already mentioned in controller v2.21.2, though!
This chart-only change makes GUNICORN_WORKERS settable from in the controller chart.
#75 will close and we can reopen with whatever changes are needed for CONN_MAX_AGE, if that's still something we want to configure. (I think we weren't convinced this other setting is really needed, whenever that conversation last left off...)
=> feat(controller): permit setting GUNICORN_WORKERS

rootfs/requirements.txt
=> chore(django): upgrade django to >= 2.2.20

charts/controller/templates/controller-clusterrole.yaml, rootfs/scheduler/mock.py, rootfs/scheduler/resources/ingress.py, rootfs/scheduler/tests/test_ingress.py
Use networking.k8s.io/v1 ingress API
This is required for K8s v1.22.0, as extensions/v1beta1 ingress was deprecated and finally is removed.
I guess we can consider promoting the ingress feature out of "experimental" now that the underlying API is in GA,  🎉 !
=> chore(ingress): update from extensions/v1beta1 to networking.k8s.io/v1

charts/controller/templates/controller-ingress-rule-http-80.yaml, charts/controller/values.yaml
The chart ingress rule needs to be updated to match the changes to controller, (in the next release we will support networking.k8s.io/v1 Ingress only, and the extensions/v1beta1 Ingress will be removed.)
The expectation is generally that people are upgrading their clusters and the older Ingress and other beta versions will be automatically upgraded, (but they must also be upgraded in the helm charts.)
Note: maybe we should add `ingressClassName` support before we release this change. It can be merged as-is, however I only stumbled upon this because I was trying to patch `ingressClassName` into the ingress rule, and I found the helm chart wasn't actually rendering the new version.
I will upgrade to K8s 1.22 again soon so we can flush out any more issues like this, (hopefully prior to …
=> chore(chart): update ingress-rule in chart

charts/controller/templates/controller-clusterrole.yaml, charts/controller/templates/controller-deployment.yaml, charts/controller/templates/controller-ingress-rule-http-80.yaml, charts/controller/values.yaml, rootfs/api/models/app.py, rootfs/api/settings/production.py
=> chore(charts): rm experimental from ingress

rootfs/Pipfile.lock
- [chore(deps): bump django from 2.2.27 to 2.2.28 in /rootfs](https://github.com/teamhephy/controller/commit/9fa4ef0b8dc29b7bfcbf2e53723d09484995d33d)
=> chore(deps): bump django from 2.2.27 to 2.2.28 in /rootfs
